AllCops:
  Exclude:
    - 'spec/dummy/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
  DisplayCopNames: true
  TargetRubyVersion: 2.5
Documentation:
  Enabled: false
# Slightly longer classes
Metrics/ClassLength:
  Max: 125
Metrics/LineLength:
  Max: 130
Metrics/MethodLength:
  Max: 25
# RSpec uses long blocks (i.e. describe, it, etc.)
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - '*.gemspec'
# New version of rubocop has these styles,
# need to set it here in order to get rid of warnings
Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: false
Layout/SpaceAroundMethodCallOperator:
  Enabled: false
Lint/DeprecatedOpenSSLConstant:
  Enabled: false
Lint/RaiseException:
  Enabled: false
Lint/StructNewOverride:
  Enabled: false
Style/ExponentialNotation:
  Enabled: false
Style/HashEachMethods:
  Enabled: false
Style/HashTransformKeys:
  Enabled: false
Style/HashTransformValues:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
