sudo: false
language: ruby
services:
  - redis-server
rvm:
  - 2.3.1
before_install:
  - npm i -g npm@5.5.1
  - npm install -g stylelint
  - gem install bundler && bundle --version
script:
  - bundle exec danger
  - bundle exec rake
  - bundle exec stylelint "app/assets/stylesheets/**/*.scss"
